### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ralphbird** [VERITAS-Observatory/V2DL3#10]
A preliminary validation list that I would like to see

- [ ] Check high stats crab spectra
- [ ] Check other spectra
- [ ] Check significances/sky maps & distributions
- [ ] Upper limitsCheck
- [ ] Light Curve

**Comment by GernotMaier** [comment]
Closing this. We are doing a lot of validation in different projects. Don't think we will ever have a complete CI based validation in V2DL3.
