### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ralphbird** [VERITAS-Observatory/V2DL3#11]
It would be good to produce a few documents to show basic running and comparisons between VERITAS and gammapy results (ideally both ED and VEGAS).  This would also be an easy intro for people into the basic usage.  Perhaps tie in with issue #10.

**Comment by GernotMaier** [comment]
I am closing this issue - writing documentation is very generic and does not need a specific issue (unless it is clearly written what should be documented)
