### ISSUE TITLE
Eventdisplay wiki needs update on how to run the converter

### ISSUE THREAD

**Issue by GernotMaier** [VERITAS-Observatory/V2DL3#113]
The following pages require updates:

- https://veritas.sao.arizona.edu/wiki/Eventdisplay_Manual:_Creating_DL3_products
- https://veritas.sao.arizona.edu/wiki/Eventdisplay_Manual:_Performing_a_gammapy_analysis

**Comment by sona-patel** [comment]
The wiki for creating DL3 products has been updated - https://veritas.sao.arizona.edu/wiki/Eventdisplay_Manual:_Creating_DL3_products#Creating_DL3_data_product

@GernotMaier @tobiaskleiner would you please have a look and comment/suggest/edit ?

**Comment by GernotMaier** [comment]
Great, thank you - looks good, I've correct a few small typos only.

Is this part still correct?
```
in the current V2DL3 implementation (described below) each DL3 file will correspond to a single run. For the moment, sub-dividing the run length into shorter files is not implemented. 
```

Please make sure that all v2dl3 specific documentation (e.g., the documentation on the fuzzy boundaries) is included in the readme of this repositories. Documentation should be as close as possible to the source code...

**Comment by sona-patel** [comment]
> in the current V2DL3 implementation (described below) each DL3 file will correspond to a single run. For the moment, sub-dividing the run length into shorter files is not implemented. 

Yes, this part is still correct. We have one DL3 file per run.

**Comment by sona-patel** [comment]
The Eventdisplay wiki page for performing a Gammapy analysis has also been updated:

https://veritas.sao.arizona.edu/wiki/Eventdisplay_Manual:_Performing_a_gammapy_analysis
