### ISSUE TITLE
Example notebooks are not working anymore.

### ISSUE THREAD

**Issue by GernotMaier** [VERITAS-Observatory/V2DL3#114]
Example notebooks in [./notebooks](https://github.com/VERITAS-Observatory/V2DL3/tree/main/notebooks) directory are not working anymore (due to gammapy updates?)

Suggest to cleanup here and have three example notebooks:
- spectral analysis (point-like)
- sky map generation
- light curve generation (point-like)

The notebooks should be independent of vegas/eventsdisplay (this is the whole point of having DL3...).

Suggest to put an example dataset for the above notebooks into these directories.
- ./vegas/point-like
- ./eventdisplay/point-like
Best would be to have the same runs for both packages (e.g., the four Crab runs 64080-64083).

Maybe start with gammapy and see of someone adds also ctools example.

**Comment by sona-patel** [comment]
The example notebooks for point-like analysis working with Gammapy-0.19 are updated.

* [spectral analysis ](https://github.com/VERITAS-Observatory/DL3-Analysis/blob/main/notebooks/VERITAS_1D_Spectrum.ipynb)
* [Lightcurve analysis](https://github.com/VERITAS-Observatory/DL3-Analysis/blob/main/notebooks/VERITAS_1D_Lightcurve.ipynb) 

The example dataset to run above notebooks:
*  [Crab dataset ](https://github.com/VERITAS-Observatory/DL3-Analysis/tree/main/notebooks/point_like)  for Spectrum analysis (64080, 64081, 64082, 64083) 
* [Mrk 421 dataset](https://github.com/VERITAS-Observatory/DL3-Analysis/tree/main/notebooks/point_like/Mrk421) for Lightcurve analysis (73196, 73197, 73198, 73199, 73200, 73201, 73202, 73203, 73204)  

**Note**: It is proposed to move the [./notebooks ](https://github.com/VERITAS-Observatory/V2DL3/tree/main/notebooks) to [DL3-Analysis](https://github.com/VERITAS-Observatory/DL3-Analysis) repository (PR #138 ).

**Comment by sona-patel** [comment]
./notebooks directory moved to [DL3-Analysis](https://github.com/VERITAS-Observatory/DL3-Analysis)!
