### ISSUE TITLE
Wrong instructions for index generation in README

### ISSUE THREAD

**Issue by pivosb** [VERITAS-Observatory/V2DL3#123]
I believe that the instructions in https://github.com/VERITAS-Observatory/V2DL3#data-storage-and-generating-index-files should say:

---
# Data storage and generating index files

Two index files are required for DL3-type analysis and can be generated with the tool `generate_index_file.py`.

The tables are descriped on the [GADF website](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/data_storage/index.html):
- [Observation index table](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/data_storage/obs_index/index.html)
- [HDU index table](https://gamma-astro-data-formats.readthedocs.io/en/v0.2/data_storage/hdu_index/index.html)

To use `generate_index_file.py`, run:
- `generate_index_file --help` when using VEGAS
**- `python pyV2DL3/script/generate_index_file.py --help` when using Eventdisplay** 

---

**Comment by sona-patel** [comment]
Thanks for issue. The index files generation instruction is updated now.
