### ISSUE TITLE
convertROOT2fits - what is it?

### ISSUE THREAD

**Issue by GernotMaier** [VERITAS-Observatory/V2DL3#149]
Not sure what this file does:

https://github.com/VERITAS-Observatory/V2DL3/blob/main/pyV2DL3/eventdisplay/convertROOT2fits.py

How is it used? It is not used as a module of any of the converter classes. If it is useful, maybe we can document it?

@sona-patel @takdg123 @tobiaskleiner

**Comment by sona-patel** [comment]
Yes, `convertROOT2fits.py` is not used in V2DL3. I think it was only used for the initial [`vtspy`](https://github.com/takdg123/vtspy) development/testing. Currently, It is only used in `vtspy` ([here](https://github.com/takdg123/vtspy/blob/1de765e3f5c59ced43d13ff0e7e39cda422324d2/vtspy/utils.py#L270)). 

@takdg123 can you please confirm or comment more?

And, I think we can removed it from this repository to avoid duplication.

**Comment by GernotMaier** [comment]
(@takdg123 confirmed that we can remove it)

**Comment by GernotMaier** [comment]
To document it: I am removing the branch dg-patch, as it includes changes to convertROOT2fits only.
