### ISSUE TITLE
qsub_convert.sh - what is this script doing

### ISSUE THREAD

**Issue by GernotMaier** [VERITAS-Observatory/V2DL3#161]
Not sure if this script is used? And if yes, for what?

https://github.com/VERITAS-Observatory/V2DL3/blob/main/pyV2DL3/script/helper/qsub_convert.sh

I think it is a leftover from earlier times. I propose to remove it, unless there are protests.

**Comment by sona-patel** [comment]
that's right! its leftover - issue #143
