### ISSUE TITLE
Wrong dimension when EFFAREA has only one wobble

### ISSUE THREAD

**Issue by epuesche** [VERITAS-Observatory/V2DL3#87]
I'm seeing a crash on the gammapy side for RHV runs, where there is only one wobble in the effective area. The error occurs when accessing the effective area. Error printout is in the attached file [gammapy_effarea.txt](https://github.com/VERITAS-Observatory/V2DL3/files/7164218/gammapy_effarea.txt), from DESY can reproduce it with this snippet:

from astropy.coordinates import Angle
import matplotlib.pyplot as plt
from gammapy.irf import EffectiveAreaTable2D

filename = "/lustre/fs23/group/veritas/users/epuesche/EBL_DL3/1ES1218/v485/GTI/65797.anasum.fits"
aeff = EffectiveAreaTable2D.read(filename, hdu="EFFECTIVE AREA")
offset = Angle("0.5 deg")
aeff_table = aeff.to_effective_area_table(offset=offset)
aeff_table.plot()
plt.show()

**Comment by GernotMaier** [comment]
@epuesche - could you test the code in branch `rhv_runs`, which should at least temporarily address this issue? I've tested it on a couple of runs, for me it seems to be fine.
